name: opinions
channels:
  - defaults
dependencies:
  - cryptography=2.7
  - flask=1.1.1
  - pip=19.0.1
  - python=3.7.2
  - python-dateutil=2.7.5
  - pyyaml=3.13
  - requests=2.21.0
  - werkzeug=0.16.1
  - yaml=0.1.7
  - pip:
    - ecological==2.0.0
    - flask-wtf==0.14.2
    - gunicorn==19.9.0
    - mypy==0.720
    - mypy-extensions==0.4.1
    - python-json-logger==0.1.11
    - redis==3.2.1
    - structlog==19.1.0
    - wtforms==2.2.1
