name: opinions
channels:
  - defaults
dependencies:
  - cryptography=2.7
  - flask=1.1.1
  - jinja2=2.10.1
  - pip=19.2.3
  - python=3.7.4
  - pyyaml=5.1.2
  - requests=2.22.0
  - urllib3=1.24.2
  - werkzeug=0.16.0
  - pip:
    - dataclasses==0.6
    - ecological==2.0.0
    - gunicorn==19.9.0
    - mypy==0.730
    - mypy-extensions==0.4.2
    - python-json-logger==0.1.11
    - python-rapidjson==0.8.0
    - redis==3.3.8
    - structlog==19.1.0
    - typed-ast==1.4.0
    - typing-extensions==3.7.4
