FROM alpine:3.10.1

ENV APP_DIR /app
EXPOSE 8007

# app dir and user
RUN apk add --no-cache build-base bash git py3-pip openssl-dev libffi-dev python3-dev \
    && pip3 install --upgrade pip \
    && addgroup -S opinions_user \
    && adduser -S -G opinions_user opinions_user \
    && mkdir ${APP_DIR} \
    && chown -R opinions_user:opinions_user ${APP_DIR} \
    && chmod -R 770 ${APP_DIR}

WORKDIR ${APP_DIR}

USER opinions_user

ADD --chown=opinions_user:opinions_user *.txt ${APP_DIR}/
ADD --chown=opinions_user:opinions_user deployment/run.sh ${APP_DIR}/
ADD --chown=opinions_user:opinions_user run.py ${APP_DIR}/
ADD --chown=opinions_user:opinions_user setup.py ${APP_DIR}/
ADD --chown=opinions_user:opinions_user README.md ${APP_DIR}/
ADD --chown=opinions_user:opinions_user deployment/setup.test ${APP_DIR}/setup.cfg
ADD --chown=opinions_user:opinions_user deployment/coveragerc ${APP_DIR}/.coveragerc

RUN pip3 install --user -r ${APP_DIR}/requirements.txt
RUN pip3 install --user -r ${APP_DIR}/testing-requirements.txt
RUN pip3 install --user -e .

# Add source code last to take advantage of Docker layer caching
ADD --chown=opinions_user:opinions_user opinions ${APP_DIR}/opinions
ADD --chown=opinions_user:opinions_user test ${APP_DIR}/test

SHELL ["/bin/bash", "-c"]
ENTRYPOINT [ "/home/opinions_user/.local/bin/pytest" ]
